npcs:
  - name: Wizard
    spawn: wizard1 # The spawn point object name in the map
    spriteSheet:
      &wizardSS
      path: images/npc.png # Path to the spritesheet within /assets
      values:
        rows: 10 # How many rows ss has
        cols: 10 # How many columns ss has
        idleRow: 5 # Which row is the idle animation
        walkRow: 7 # Which row is the walk animation
    movement:
      &wizardMovement
      speed: 0.5
      maxVelocity: 5
    size:
      &wizardSize
      height: 2.5
      width: 2.7
    dialogs:
      - &dialog3
        textID: dialog3
        choices:
          - &bye
            textID: choice3 # Bye
      - &dialog2
        textID: dialog2
        choices:
          - *bye
      - textID: dialog1
        choices:
          - textID: choice1 # Accept
            next: *dialog3
          - textID: choice2 # Deny
            next: *dialog2
  - name: Villager
    spawn: villager1
    spriteSheet:
      *wizardSS
    movement:
      *wizardMovement
    size:
      *wizardSize
    dialogs:
      - textID: dialog4
        choices:
          - textID: choice3 # Bye
    schedules:
      - hour: 0
        minute: 30
        nodes:
          - id: villager3s
          - id: villager4s